name:                si-calculator
version:             0.1.0.0
license:             BSD-3-Clause
author:              "Lukas Pietzschmann, Thomas Schöller"
maintainer:          "Lukas Pietzschmann, Thomas Schöller"
copyright:           "2024 Lukas Pietzschmann, Thomas Schöller"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/si-calculator#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - template-haskell
  - mtl
  - containers

executables:
  si-calculator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - si-calculator
    - haskeline

tests:
  si-calculator-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - si-calculator
    - tasty
    - tasty-hunit
    - tasty-quickcheck
